# -*- coding: utf-8 -*-
"""recipe_with_genres.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FF3tYqUwQX2GWozkT49v66LZagrrrGXB
"""

# 판다스 패키지 임포트
import pandas as pd
pd.__version__

# 레시피 데이터 읽어오기
recipe = pd.read_csv('../../crawler/curry_recipe.csv', index_col = 'id')

recipe.sample()

# 장르 열 추가
recipe['genres'] = ""

recipe.sample()

# ing 목록
ing1 = ['소고기', '쇠고기', '소불고기', 'LA갈비', '한우']
ing2 = ['돼지', '돼지고기', '목살', '삼겹살', '베이컨', '스팸', '소시지', '소세지', '김밥용햄', '김밥용 햄', '모듬햄', ' 햄 ', '슬라이스햄', '통조림햄', '슬라이스 햄', '통조림 햄']
ing3 = ['닭']
ing4 = ['오리고기', '훈제오리']
ing5 = ['가자미', '광어', '도미', '민어', '멸치 ', '고등어', '꽁치', '장어', '연어', '청어', '메기', '붕어', '빙어', '잉어', '송어', '참치', '갈치', '농어', '명태', '정어리', '삼치', '동태']
ing6 = ['꼴뚜기', '낙지', '문어', '오징어', '해삼', '해파리', '쭈꾸미', '주꾸미']
ing7 = ['가재', '왕게', '킹크랩', '랍스터', '새우 ', '대게', '게살', '꽃게', '게장', '게맛살', '크래미']
ing8 = ['가리비', '대합', '모시조개', '바지락', '소라', '우렁', '전복', '홍합', '꼬막', ' 굴 ', '생굴']
ing9 = ['김치', '깍두기', '묵은지']
ing10 = ['두부']
ing11 = ['달걀', '계란', '노른자', '메추리알']
ing12 = ['버섯', '표고']
ing13 = ['갓', '근대', '머위', '무청', '미나리', '양배추', '배추', '봄동', '상추', '샐러리', '시금치', '쑥갓', '깻잎', ' 냉이 ', '고사리', '콩나물', '숙주', '청경채', '치커리']
ing14 = ['두릅', '마늘쫑', '부추', '샐러리', '셀러리', '아스파라거스', '염교', '죽순', '참나리', '송송썬파', '쪽파', '대파', '다진파', '파채', '실파', ' 파 ']
ing15 = ['당근', '래디쉬', '비트', '생강', '순무', '연근', '우엉', '토란', '고구마', '감자', '옥수수', ' 무 ', '무절임', '열무']
ing16 = ['마늘', '샬롯', '양파']
ing17 = ['가지', '고추', '동아', '오이', '월과', '피망', '토마토', '호박', '파프리카']
ing18 = ['브로콜리', '아티초크', '양하', '콜리플라워']
ing19 = ['사과', '유자', '자몽', '오렌지', '라임', '레몬', '갈은배', '배즙', '배음료', ' 배 ', '갈아만든배', '곶감', '단감', ' 감 ', '귤', '한라봉']
ing20 = ['복숭아', '매실', '살구', '자두', '대추', '앵두']
ing21 = ['포도', '무화과', '석류', '크랜베리', '블루베리', '체리', '라즈베리']
ing22 = ['바나나', '파인애플', '키위', '아보카도', '망고']
ing23 = ['호두', '은행', '견과류', '콩 ', '아몬드', '밤', '잣', '팥']
ing24 = ['딸기', '수박', '참외']
ing25 = ['우유', '아이스크림', '치즈', '버터', '요구르트']

# ing 처리
def update_genres(row):
    temp_ingredients = row['ingredients'].replace('|', ' ')  # 임시로 복사하여 '|'를 ' '로 변경

    for i in range(1, 26):
        ing_list = globals()[f'ing{i}']
        for ing in ing_list:
            if ing in temp_ingredients and f'ing{i}|' not in row['genres']:
                row['genres'] += f'ing{i}|'
                break
    return row

recipe = recipe.apply(update_genres, axis=1)

# 마지막 | 삭제
recipe['genres'] = recipe['genres'].str.rstrip('|')

# 장르 추가 확인
recipe.sample()

# 장르가 하나도 없는 레시피 확인
empty_genre_rows = recipe[recipe['genres'] == '']
empty_genre_rows

# csv 파일 내보내기
recipe.to_csv('curry_recipe_with_genres.csv', encoding='utf-8-sig')

# 장르 데이터 숫자형으로 변환
genres_dumies = recipe['genres'].str.get_dummies(sep='|')
genres_dumies.sample()

# 열 순서 변경
genres_dumies = genres_dumies.reindex(columns=['ing1', 'ing2', 'ing3', 'ing4', 'ing5', 'ing6', 'ing7', 'ing8', 'ing9', 'ing10', 'ing11', 'ing12', 'ing13', 'ing14', 'ing15', 'ing16', 'ing17', 'ing18', 'ing19', 'ing20', 'ing21', 'ing22', 'ing23', 'ing24', 'ing25'])
genres_dumies.sample()

# 장르 데이터프레임 내보내기
genres_dumies.to_csv('genres.csv', encoding='utf-8-sig')