# -*- coding: utf-8 -*-
"""ratings_sample.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12f9o7PMB2pbvlSeGFiWNtkwSJD_cvQta

# 장르가 나누어진 데이터를 가지고 평점 매기기

## 레시피 데이터 받아오기
"""

import pandas as pd

# 샘플로 작성
# recipes = pd.read_csv('/content/drive/MyDrive/curry_data/curry_recipe_genre_sample.csv', index_col='id')
recipes = pd.read_csv('/content/drive/MyDrive/curry_data/curry_recipe_genre_sample.csv')
recipes

recipes['genre']

"""## 페르소나 (가상 유저) 데이터 프레임 생성"""

# 샘플로 작성 - 페르소나 2, 3, 27, 34번 유저
personae = [[1, 'ing21|ing5|ing16', 'ing25'], [2, 'ing17|ing22|ing25', 'ing11'], [3, 'ing10|ing18|ing2', 'ing25'], [4, 'ing1', 'ing23|ing12|ing14']]
personae = pd.DataFrame(personae, columns=['userId', 'Good', 'Bad'])
# personae.set_index('userId', inplace=True)

personae

"""## 페르소나의 선호 장르 데이터를 이용하여 레시피 평점 계산하기"""

import re

ratings = []

for index, user in personae.iterrows():
  for idx, recipe in recipes.iterrows():
    recipe_genre_list = recipe['genre'].split('|')
    personae_good = user['Good'].split('|')
    personae_bad = user['Bad'].split('|')
    rating = 5
    for j in recipe_genre_list:
      for p in personae_good:
        if (j == p):
          rating += 1
      for q in personae_bad:
        if (j == q):
          rating -= 1
  # print(user['userId'])
  # print(recipes.loc[index, 'id'])
    print(recipe['id'])
    ratings.append([recipe['id'], user['userId'], rating])
ratings = pd.DataFrame(ratings, columns=['id', 'userId', 'rating'])

ratings

recipe_ratings = pd.merge(recipes, ratings, how='outer', on='id')
recipe_ratings