# -*- coding: utf-8 -*-
"""recipe_with_genres.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FF3tYqUwQX2GWozkT49v66LZagrrrGXB
"""

# 판다스 패키지 임포트
import pandas as pd
pd.__version__

from google.colab import drive
drive.mount('/content/drive')

# 레시피 데이터 읽어오기
recipe = pd.read_csv('/content/drive/MyDrive/추천 시스템/curry_recipe.csv', index_col = 'id')

recipe.sample()

# 장르 열 추가
recipe['genres'] = ""

recipe.sample()

# ing 목록 (햄 제외)
ing1 = ['소고기', '쇠고기', '소불고기', 'LA갈비', '한우']
ing2 = ['돼지', '돼지고기', '목살', '삼겹살', '베이컨', '스팸', '소시지', '소세지']
ing3 = ['닭']
ing4 = ['오리고기', '훈제오리']
ing5 = ['가자미', '광어', '도미', '민어', '고등어', '꽁치', '멸치', '장어', '연어', '청어', '메기', '붕어', '빙어', '잉어', '송어', '참치', '갈치', '농어', '명태', '정어리', '삼치', '동태']
ing6 = ['꼴뚜기', '낙지', '문어', '오징어', '해삼', '해파리', '쭈꾸미', '주꾸미']
ing7 = ['가재', '게', '새우', '왕게', '킹크랩', '랍스터']
ing8 = ['가리비', '굴', '대합', '모시조개', '바지락', '소라', '우렁', '전복', '홍합', '꼬막']
ing9 = ['김치', '깍두기', '묵은지']
ing10 = ['달걀', '계란', '노른자', '메추리알']
ing11 = ['갓', '근대', '머위', '무청', '미나리', '양배추', '배추', '상추', '샐러리', '시금치', '쑥갓', '깻잎', '냉이', '고사리', '콩나물', '숙주', '청경채', '치커리']
ing12 = ['두릅', '마늘쫑', '부추', '샐러리', '셀러리', '아스파라거스', '염교', '죽순', '참나리', '파']
ing13 = ['당근', '래디쉬', '무', '비트', '생강', '순무', '연근', '우엉', '토란', '고구마', '감자', '옥수수']
ing14 = ['마늘', '샬롯', '양파']
ing15 = ['가지', '고추', '동아', '박', '오이', '월과', '피망', '토마토', '호박']
ing16 = ['브로콜리', '아티초크', '양하', '콜리플라워']
ing17 = ['사과', '배', '감', '귤', '유자', '자몽', '오렌지', '라임', '레몬']
ing18 = ['복숭아', '매실', '살구', '자두', '대추', '앵두']
ing19 = ['포도', '무화과', '석류', '크랜베리', '블루베리', '체리', '라즈베리']
ing20 = ['바나나', '파인애플', '키위', '아보카도', '망고']
ing21 = ['밤', '호두', '은행', '견과류', '땅콩', '아몬드', '잣']
ing22 = ['딸기', '수박', '참외']
ing23 = ['버섯', '표고']
ing24 = ['두부']
ing25 = ['우유', '아이스크림', '치즈', '버터', '요구르트']

# ing 처리
def update_genres(row):
    for i in range(1, 26):
        ing_list = globals()[f'ing{i}']
        for ing in ing_list:
            if ing in row['ingredients'] and f'ing{i}|' not in row['genres']:
                row['genres'] += f'ing{i}|'
                break
    return row

recipe = recipe.apply(update_genres, axis=1)

# ing2에서 햄 따로 처리
def update_ham(row):
    if '햄' in row['ingredients'] and 'ing1|' not in row['genres']:
        if '햄버거빵' not in row['ingredients']:
            row['genres'] += 'ing1|'
    return row

recipe = recipe.apply(update_ham, axis=1)

# 마지막 | 삭제
recipe['genres'] = recipe['genres'].str.rstrip('|')

# 장르 추가 확인
recipe.sample()

# 장르가 하나도 없는 레시피 확인
empty_genre_rows = recipe[recipe['genres'] == '']
empty_genre_rows

# csv 파일 내보내기
recipe.to_csv('curry_recipe_with_genres.csv', encoding='utf-8-sig')

# 장르 데이터 숫자형으로 변환
genres_dumies = recipe['genres'].str.get_dummies(sep='|')
genres_dumies.sample()

# 열 순서 변경
genres_dumies = genres_dumies.reindex(columns=['ing1', 'ing2', 'ing3', 'ing4', 'ing5', 'ing6', 'ing7', 'ing8', 'ing9', 'ing10', 'ing11', 'ing12', 'ing13', 'ing14', 'ing15', 'ing16', 'ing17', 'ing18', 'ing19', 'ing20', 'ing21', 'ing22', 'ing23', 'ing24', 'ing25'])
genres_dumies.sample()

# 장르 데이터프레임 내보내기
genres_dumies.to_pickle('genres.p')