name: Flask Docker Image CI

on:
  push:
    branches: [ "deploy" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  DOCKER_IMAGE_NAME: flask
  GCE_INSTANCE: ${{ secrets.GCE_INSTANCE }}
  GCE_INSTANCE_ZONE: ${{ secrets.GCE_INSTANCE_ZONE}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true    
    - run: |-
          gcloud auth configure-docker
    
    - name: Flask Docker Image Build
      run: |-
          docker build . --file Dockerfile --tag "gcr.io/$PROJECT_ID/$DOCKER_IMAGE_NAME:latest

    - name: Flask Docker Image Push
      run: |-
          docker push "gcr.io/$PROJECT_ID/$DOCKER_IMAGE_NAME:latest"

    - name: Deploy to Google Compute Engine
      run: |-
          gcloud compute instances update-container "$GCE_INSTANCE" \
            --zone "$GCE_INSTANCE_ZONE" \
            --container-image "gcr.io/$PROJECT_ID/$DOCKER_IMAGE_NAME:latest"
